import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faLinkedinIn as linkedin, faTwitter as twitter, faGithub as github } from '@fortawesome/free-brands-svg-icons';

export default function Home() {
  const introString = "// My self introduction";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <header className={styles.header}>
        <div className={styles.name}>ENGINEER</div>
        <div>
          <nav>
            <ul>
              <li><a>HOME</a></li>
              <li><a>ABOUT</a></li>
              <li><a>TECH</a></li>
              <li><a>PROJECTS</a></li>
            </ul>
          </nav>
        </div>
        <div className={styles.contact}>
          <a>
            GET IN TOUCH
          </a>
        </div>
      </header>

      <main className={styles.main}>
        <section className={styles.intro}>
          <div className={styles.intro_inner_container}>
            <h2 className={styles.hello}>Hello</h2>
            <h3 className={styles.title}>I&apos;m Anubhav</h3>
            <div className={styles.intro_one_container}>
              <p style={{color: "#586c7a"}}>{introString}</p>
              <p><span style={{color: "#ec91ff"}}>name</span> &#123;</p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;first_name: <span style={{color: "#73d9ff"}}>&quot;Anubhav&quot;</span></p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;last_name: <span style={{color: "#73d9ff"}}>&quot;Bhambri&quot;</span></p>
              <p className={styles.closing_bracket}>&#125;</p>
            </div>
            <div className={styles.intro_two_container}>
              <p><span style={{color: "#ec91ff"}}>what_i_do</span> &#123;</p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;profession: <span style={{color: "#73d9ff"}}>&quot;Developer&quot;</span></p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expertise: <span style={{color: "#73d9ff"}}>&quot;Backend&quot;</span></p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;language: <span style={{color: "#73d9ff"}}>&quot;Javascript&quot;</span></p>
              <p className={styles.closing_bracket}>&#125;</p>
            </div>
          </div>
        </section>

        <section className={styles.experience}>
          <div className={styles.experience_inner_container}>
            <div style={{ marginBottom: "70px" }}>
              <h2>
                <strong>#05</strong>
                <br />
                Years
                <strong>;</strong>
              </h2>
              <p>It&apos;s the 31st of December and 2015 is about to end. For so many years I have had been reading posts from different software developers about how they spent the year and how they were planning.</p>
            </div>
            <div className={styles.experience_cards_container}>
              <div className={styles.experience_card_container}>
                <h2>
                  2019
                </h2>
                <h3>
                  Back-End Developer
                </h3>
                <p>
                  It’s the 31st of December and 2015 is about to end. For so many years I have had been reading. dummy text
                </p>
              </div>
              <div className={styles.experience_card_container} style={{marginTop: "100px"}}>
                <h2>
                  2019
                </h2>
                <h3>
                  Back-End Developer
                </h3>
                <p>
                  It’s the 31st of December and 2015 is about to end. For so many years I have had been reading. dummy text
                </p>
              </div>
              <div className={styles.experience_card_container}>
                <h2>
                  2019
                </h2>
                <h3>
                  Back-End Developer
                </h3>
                <p>
                  It’s the 31st of December and 2015 is about to end. For so many years I have had been reading. dummy text
                </p>
              </div>
              <div className={styles.experience_card_container} style={{marginTop: "100px"}}>
                <h2>
                  2019
                </h2>
                <h3>
                  Back-End Developer
                </h3>
                <p>
                  It&apos;s the 31st of December and 2015 is about to end. For so many years I have had been reading. dummy text
                </p>
              </div>
            </div>
          </div>
        </section>

        <div className={styles.divider}></div>

        <section className={styles.projects}>
          <div className={styles.projects_inner_container}>
            <h2>#Latest Works</h2>
            <h3>Digital Explorers is a knowledge exchange initiative between 2 buzzing ICT markets, offering.</h3>
          </div>
        </section>

        <section className={styles.labs}>
          <div className={styles.labs_inner_container}>
            <div style={{marginBottom: "70px"}}>
              <h2>#Lab;</h2>
              <p>It’s the 31st of December and 2015 is about to end. For so many years I have had been readfferent software.</p>
            </div>
            <div className={styles.labs_cards_container}>
              <div className={styles.labs_card_container}>
                <h2>Codepen</h2>
                <p>Select Your Coding Hero! Ghost Boo-sters ? - the game ? 408 Request Timeout - Physics Game ? FaceDetection Mask App ? Rocket Lauch Game ? HODOR 403 ✋ ?⚔️ Back2School SVG - anime.js</p>
              </div>
              <div className={styles.labs_card_container}>
                <h2>Codepen</h2>
                <p>Select Your Coding Hero! Ghost Boo-sters ? - the game ? 408 Request Timeout - Physics Game ? FaceDetection Mask App ? Rocket Lauch Game ? HODOR 403 ✋ ?⚔️ Back2School SVG - anime.js</p>
              </div>
              <div className={styles.labs_card_container}>
                <h2>Codepen</h2>
                <p>Select Your Coding Hero! Ghost Boo-sters ? - the game ? 408 Request Timeout - Physics Game ? FaceDetection Mask App ? Rocket Lauch Game ? HODOR 403 ✋ ?⚔️ Back2School SVG - anime.js</p>
              </div>
            </div>
          </div>
        </section>

        <section className={styles.socials}>
          <div className={styles.socials_inner_container}>
            <div className={styles.heading_container}>

              <h2 className={styles.shy}>Don&apos;t be shy,</h2>
              <h2 className={styles.hi}>say hi;</h2>
            </div>
            <div className={styles.lower_container}>
              <div className={styles.left_div}>
                <div className={styles.social_link}>
                  <div className={styles.icon_container}>
                    <FontAwesomeIcon className={styles.icons} icon={linkedin} />
                  </div>
                  <p>/in/anubhav-bhambri</p>
                </div>
                <div className={styles.social_link}>
                  <div className={styles.icon_container}>
                    <FontAwesomeIcon className={styles.icons} icon={twitter} />
                  </div>
                  <p>/anubhav_bhambri</p>
                </div>
                <div className={styles.social_link}>
                  <div className={styles.icon_container}>
                    <FontAwesomeIcon className={styles.icons} icon={github} />
                  </div>
                  <p>/Anubhav311</p>
                </div>
              </div>
              <div className={styles.right_div}>
                <p><span>Start a project?</span></p>
                <p>anubhavbhambri1@gmail.com</p>
              </div>
            </div>
          </div>
        </section>

        <div className={styles.gray_divider}></div>

      </main>

      <footer className={styles.footer}>
        <div className={styles.footer_inner_container}>
          <nav>
            <ul>
              <li><a>HOME</a></li>
              <li><a>ABOUT</a></li>
              <li><a>TECH</a></li>
              <li><a>PROJECTS</a></li>
            </ul>
          </nav>
          <div>
            <p>&#169; 2022 All Rights Reserved</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
